#
# Install vendor package
#
FROM node:16-alpine3.16 as node

# Install git
RUN apk add --no-cache git \
    py3-pip make g++

# Set bit registry
FROM chaosxy/node:16-alpine3.16-pyton3 as build
RUN npm config set @bit:registry https://node.bit.dev
WORKDIR /var/www

COPY . /var/www
COPY ./app.prod.html /var/www/app.html
COPY .env.example /var/www/.env

RUN cp /usr/bin/python3 /usr/bin/python && \
    npm install --omit=optional --legacy-peer-deps && npm run build


FROM chaosxy/node:16-alpine3.16-pyton3 as app
RUN npm config set @bit:registry https://node.bit.dev
WORKDIR /var/www
COPY --from=build /var/www/ /var/www/
COPY ./docker/start.sh /usr/bin/start.sh
RUN rm -rf node_modules && npm install --only=product --legacy-peer-deps
RUN chmod +x /usr/bin/start.sh

ENTRYPOINT ["start.sh"]
#
# Build application
#
# FROM node:14.15.5-alpine3.11

# ENV NODE_PATH=/usr/local/lib/node_modules
# COPY . /var/www
# COPY ./package-product.json /var/www/package.json
# COPY --from=build /app/static/ /var/www/static
# COPY --from=build /app/.nuxt/ /var/www/.nuxt
# RUN cd /var/www && npm i --product
# WORKDIR /var/www
