#
# Install vendor package
#
FROM node:14.15.5-alpine3.11 as build

# Install git
RUN apk add --no-cache git \
    python make g++

# Set bit registry
RUN npm config set @bit:registry https://node.bit.dev

COPY . /var/www
COPY ./package-product.json /var/www/package.json
COPY ./app.prod.html /var/www/app.html
RUN cd /var/www && npm install
WORKDIR /var/www
#
# Build application
#
# FROM node:14.15.5-alpine3.11

# ENV NODE_PATH=/usr/local/lib/node_modules
# COPY . /var/www
# COPY ./package-product.json /var/www/package.json
# COPY --from=build /app/static/ /var/www/static
# COPY --from=build /app/.nuxt/ /var/www/.nuxt
# RUN cd /var/www && npm i --product
# WORKDIR /var/www
